import {
  BadRequestException,
  ForbiddenException,
  Inject,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { and, asc, count, desc, eq, gt, inArray, isNull, lt, ne, or, sql } from 'drizzle-orm';
import {
  ConversationType,
  type ChatAttachment,
  type ChatContact,
  type ChatMessage,
  type ConversationDetail,
  type ConversationMember,
  type ConversationSummary,
  type SendMessageInput,
  type UserRef,
} from '@task-tracker/shared';
import { DRIZZLE, type Database } from '../database/database.module';
import {
  conversationMembers,
  conversations,
  messageAttachments,
  messageMentions,
  messageReactions,
  messages,
  projects,
  users,
  workspaceMembers,
  type ConversationRow,
  type MessageRow,
} from '../database/schema';
import { WorkspacesService } from '../workspaces/workspaces.service';

type Actor = { id: string; role: string };

/** Attachment keys are server-generated by FilesService; format-check before linking. */
const ATTACHMENT_KEY = /^attachments\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.[a-z0-9]{2,5}$/;

/** Stable "<minId>:<maxId>" key so a DM between two users resolves to one row. */
function directKey(a: string, b: string): string {
  return a < b ? `${a}:${b}` : `${b}:${a}`;
}

@Injectable()
export class ChatService {
  constructor(
    @Inject(DRIZZLE) private readonly db: Database,
    private readonly workspaces: WorkspacesService,
  ) {}

  private toUserRef(u: { id: string; name: string; email: string; avatarKey: string | null }): UserRef {
    return { id: u.id, name: u.name, email: u.email, avatarKey: u.avatarKey };
  }

  private async loadConversation(conversationId: string): Promise<ConversationRow> {
    const [row] = await this.db
      .select()
      .from(conversations)
      .where(eq(conversations.id, conversationId))
      .limit(1);
    if (!row) throw new NotFoundException('Conversation not found');
    return row;
  }

  /** workspaceId for a PROJECT conversation (used for dynamic authorization). */
  private async projectWorkspaceId(projectId: string): Promise<string> {
    const [p] = await this.db
      .select({ workspaceId: projects.workspaceId })
      .from(projects)
      .where(eq(projects.id, projectId))
      .limit(1);
    if (!p) throw new NotFoundException('Project not found');
    return p.workspaceId;
  }

  /** Insert a membership row if absent (used to lazily materialise read-state). */
  private async ensureMemberRow(conversationId: string, userId: string): Promise<void> {
    await this.db
      .insert(conversationMembers)
      .values({ conversationId, userId })
      .onConflictDoNothing({ target: [conversationMembers.conversationId, conversationMembers.userId] });
  }

  private async isExplicitMember(conversationId: string, userId: string): Promise<boolean> {
    const [row] = await this.db
      .select({ id: conversationMembers.id })
      .from(conversationMembers)
      .where(and(eq(conversationMembers.conversationId, conversationId), eq(conversationMembers.userId, userId)))
      .limit(1);
    return !!row;
  }

  /**
   * Authorize an actor for a conversation and return its row.
   * DIRECT/GROUP → strict membership (admins get no bypass — chat is private).
   * PROJECT → workspace membership; a read-state row is materialised on first access.
   */
  async assertCanAccess(conversationId: string, actor: Actor): Promise<ConversationRow> {
    const conv = await this.loadConversation(conversationId);
    if (conv.type === ConversationType.PROJECT) {
      const workspaceId = await this.projectWorkspaceId(conv.projectId!);
      await this.workspaces.assertCanAccess(workspaceId, actor);
      await this.ensureMemberRow(conversationId, actor.id);
      return conv;
    }
    if (!(await this.isExplicitMember(conversationId, actor.id))) {
      throw new ForbiddenException('You are not a member of this conversation');
    }
    return conv;
  }

  /* ── Conversation listing / summaries ── */

  async listConversationIds(userId: string): Promise<string[]> {
    const rows = await this.db
      .select({ id: conversationMembers.conversationId })
      .from(conversationMembers)
      .where(eq(conversationMembers.userId, userId));
    return rows.map((r) => r.id);
  }

  async listConversations(actor: Actor): Promise<ConversationSummary[]> {
    const memberRows = await this.db
      .select({ conv: conversations, lastReadAt: conversationMembers.lastReadAt })
      .from(conversationMembers)
      .innerJoin(conversations, eq(conversations.id, conversationMembers.conversationId))
      .where(eq(conversationMembers.userId, actor.id));
    if (memberRows.length === 0) return [];

    const ids = memberRows.map((r) => r.conv.id);
    const lastReadByConv = new Map(memberRows.map((r) => [r.conv.id, r.lastReadAt]));
    const summaries = await this.buildSummaries(
      memberRows.map((r) => r.conv),
      actor.id,
      lastReadByConv,
      ids,
    );
    // Newest activity first; conversations with no messages sort by creation.
    return summaries.sort((a, b) => {
      const at = a.lastMessageAt ?? '';
      const bt = b.lastMessageAt ?? '';
      return bt.localeCompare(at);
    });
  }

  async getConversationSummary(conversationId: string, userId: string): Promise<ConversationSummary> {
    const conv = await this.loadConversation(conversationId);
    const [memberRow] = await this.db
      .select({ lastReadAt: conversationMembers.lastReadAt })
      .from(conversationMembers)
      .where(
        and(eq(conversationMembers.conversationId, conversationId), eq(conversationMembers.userId, userId)),
      )
      .limit(1);
    const lastReadByConv = new Map([[conversationId, memberRow?.lastReadAt ?? null]]);
    const [summary] = await this.buildSummaries([conv], userId, lastReadByConv, [conversationId]);
    return summary!;
  }

  /** Assemble ConversationSummary[] with batched title/preview/unread queries. */
  private async buildSummaries(
    convs: ConversationRow[],
    userId: string,
    lastReadByConv: Map<string, Date | null>,
    ids: string[],
  ): Promise<ConversationSummary[]> {
    const directIds = convs.filter((c) => c.type === ConversationType.DIRECT).map((c) => c.id);
    const projectIds = convs
      .filter((c) => c.type === ConversationType.PROJECT && c.projectId)
      .map((c) => c.projectId!);

    const [memberCounts, otherMembers, projectNames, lastMessages, unreadRows] = await Promise.all([
      this.db
        .select({ conversationId: conversationMembers.conversationId, c: count() })
        .from(conversationMembers)
        .where(inArray(conversationMembers.conversationId, ids))
        .groupBy(conversationMembers.conversationId),
      directIds.length
        ? this.db
            .select({
              conversationId: conversationMembers.conversationId,
              id: users.id,
              name: users.name,
              email: users.email,
              avatarKey: users.avatarKey,
            })
            .from(conversationMembers)
            .innerJoin(users, eq(users.id, conversationMembers.userId))
            .where(
              and(
                inArray(conversationMembers.conversationId, directIds),
                ne(conversationMembers.userId, userId),
              ),
            )
        : Promise.resolve([] as { conversationId: string; id: string; name: string; email: string; avatarKey: string | null }[]),
      projectIds.length
        ? this.db
            .select({ id: projects.id, name: projects.name, workspaceId: projects.workspaceId })
            .from(projects)
            .where(inArray(projects.id, projectIds))
        : Promise.resolve([] as { id: string; name: string; workspaceId: string }[]),
      // Latest message per conversation (including soft-deleted, for an accurate preview).
      this.db
        .selectDistinctOn([messages.conversationId], {
          conversationId: messages.conversationId,
          body: messages.body,
          deletedAt: messages.deletedAt,
          createdAt: messages.createdAt,
          senderId: messages.senderId,
          senderName: users.name,
          attachmentCount: sql<number>`(select count(*) from ${messageAttachments} ma where ma.message_id = ${messages.id})`,
        })
        .from(messages)
        .innerJoin(users, eq(users.id, messages.senderId))
        .where(inArray(messages.conversationId, ids))
        .orderBy(messages.conversationId, desc(messages.createdAt)),
      // Unread = messages after my lastReadAt, not mine, not deleted.
      this.db
        .select({ conversationId: messages.conversationId, c: count() })
        .from(messages)
        .innerJoin(
          conversationMembers,
          and(
            eq(conversationMembers.conversationId, messages.conversationId),
            eq(conversationMembers.userId, userId),
          ),
        )
        .where(
          and(
            inArray(messages.conversationId, ids),
            ne(messages.senderId, userId),
            isNull(messages.deletedAt),
            or(
              isNull(conversationMembers.lastReadAt),
              gt(messages.createdAt, conversationMembers.lastReadAt),
            ),
          ),
        )
        .groupBy(messages.conversationId),
    ]);

    const memberCountBy = new Map(memberCounts.map((r) => [r.conversationId, Number(r.c)]));
    const otherBy = new Map(otherMembers.map((r) => [r.conversationId, r]));
    const projectBy = new Map(projectNames.map((p) => [p.id, p]));
    const lastBy = new Map(lastMessages.map((m) => [m.conversationId, m]));
    const unreadBy = new Map(unreadRows.map((r) => [r.conversationId, Number(r.c)]));

    return convs.map((c) => {
      const other = otherBy.get(c.id);
      const project = c.projectId ? projectBy.get(c.projectId) : undefined;
      const last = lastBy.get(c.id);
      let title = c.title ?? '';
      let otherUser: UserRef | null = null;
      let workspaceId: string | null = null;
      if (c.type === ConversationType.DIRECT) {
        otherUser = other ? this.toUserRef(other) : null;
        title = other?.name ?? 'Direct message';
      } else if (c.type === ConversationType.PROJECT) {
        title = project?.name ?? 'Project channel';
        workspaceId = project?.workspaceId ?? null;
      }
      return {
        id: c.id,
        type: c.type as ConversationType,
        title,
        projectId: c.projectId,
        workspaceId,
        otherUser,
        memberCount: memberCountBy.get(c.id) ?? 0,
        lastMessage: last
          ? {
              body: last.deletedAt ? null : last.body,
              senderId: last.senderId,
              senderName: last.senderName,
              hasAttachment: Number(last.attachmentCount) > 0,
              createdAt: last.createdAt.toISOString(),
            }
          : null,
        lastMessageAt: c.lastMessageAt ? c.lastMessageAt.toISOString() : null,
        unreadCount: unreadBy.get(c.id) ?? 0,
      };
    });
  }

  /* ── Conversation creation ── */

  async getOrCreateDirect(actor: Actor, otherUserId: string): Promise<{ summary: ConversationSummary; created: boolean; memberIds: string[] }> {
    if (otherUserId === actor.id) throw new BadRequestException('You cannot message yourself');
    const [other] = await this.db
      .select({ id: users.id, isActive: users.isActive })
      .from(users)
      .where(eq(users.id, otherUserId))
      .limit(1);
    if (!other || !other.isActive) throw new NotFoundException('User not found');

    const key = directKey(actor.id, otherUserId);
    let created = false;
    let [conv] = await this.db.select().from(conversations).where(eq(conversations.dmKey, key)).limit(1);
    if (!conv) {
      conv = await this.db.transaction(async (tx) => {
        const [row] = await tx
          .insert(conversations)
          .values({ type: ConversationType.DIRECT, dmKey: key, createdById: actor.id })
          .onConflictDoNothing({ target: conversations.dmKey })
          .returning();
        if (!row) {
          // Lost a race — the other insert won; return the existing row.
          const [existing] = await tx.select().from(conversations).where(eq(conversations.dmKey, key)).limit(1);
          return existing!;
        }
        await tx.insert(conversationMembers).values([
          { conversationId: row.id, userId: actor.id },
          { conversationId: row.id, userId: otherUserId },
        ]);
        created = true;
        return row;
      });
    }
    const summary = await this.getConversationSummary(conv.id, actor.id);
    return { summary, created, memberIds: [actor.id, otherUserId] };
  }

  async createGroup(
    actor: Actor,
    input: { title: string; memberIds: string[] },
  ): Promise<{ summary: ConversationSummary; memberIds: string[] }> {
    const memberIds = Array.from(new Set([actor.id, ...input.memberIds]));
    const found = await this.db
      .select({ id: users.id })
      .from(users)
      .where(and(inArray(users.id, memberIds), eq(users.isActive, true)));
    const validIds = new Set(found.map((u) => u.id));
    if (!input.memberIds.every((id) => validIds.has(id))) {
      throw new BadRequestException('One or more members are not valid users');
    }

    const conv = await this.db.transaction(async (tx) => {
      const [row] = await tx
        .insert(conversations)
        .values({ type: ConversationType.GROUP, title: input.title, createdById: actor.id })
        .returning();
      await tx.insert(conversationMembers).values(
        memberIds.map((userId) => ({
          conversationId: row!.id,
          userId,
          isAdmin: userId === actor.id,
        })),
      );
      return row!;
    });
    const summary = await this.getConversationSummary(conv.id, actor.id);
    return { summary, memberIds };
  }

  async ensureProjectConversation(actor: Actor, projectId: string): Promise<ConversationSummary> {
    const workspaceId = await this.projectWorkspaceId(projectId);
    await this.workspaces.assertCanAccess(workspaceId, actor);

    let [conv] = await this.db
      .select()
      .from(conversations)
      .where(eq(conversations.projectId, projectId))
      .limit(1);
    if (!conv) {
      const [row] = await this.db
        .insert(conversations)
        .values({ type: ConversationType.PROJECT, projectId, createdById: actor.id })
        .onConflictDoNothing({ target: conversations.projectId })
        .returning();
      conv = row ?? (await this.db.select().from(conversations).where(eq(conversations.projectId, projectId)).limit(1))[0]!;
    }
    await this.ensureMemberRow(conv.id, actor.id);
    return this.getConversationSummary(conv.id, actor.id);
  }

  /* ── Messages ── */

  private async hydrateMessages(
    rows: {
      id: string;
      conversationId: string;
      senderId: string;
      body: string | null;
      editedAt: Date | null;
      deletedAt: Date | null;
      createdAt: Date;
      parentMessageId: string | null;
      senderName: string;
      senderEmail: string;
      senderAvatar: string | null;
    }[],
  ): Promise<ChatMessage[]> {
    if (rows.length === 0) return [];
    const ids = rows.map((r) => r.id);
    const parentIds = rows.map((r) => r.parentMessageId).filter((id): id is string => !!id);

    const [atts, mentions, reactions, parents] = await Promise.all([
      this.db.select().from(messageAttachments).where(inArray(messageAttachments.messageId, ids)),
      this.db
        .select({ messageId: messageMentions.messageId, userId: messageMentions.userId })
        .from(messageMentions)
        .where(inArray(messageMentions.messageId, ids)),
      this.db
        .select()
        .from(messageReactions)
        .where(inArray(messageReactions.messageId, ids)),
      parentIds.length > 0
        ? this.db
            .select({
              id: messages.id,
              body: messages.body,
              senderName: users.name,
            })
            .from(messages)
            .innerJoin(users, eq(users.id, messages.senderId))
            .where(inArray(messages.id, parentIds))
        : Promise.resolve([] as { id: string; body: string | null; senderName: string }[]),
    ]);

    const attsBy = new Map<string, ChatAttachment[]>();
    for (const a of atts) {
      const list = attsBy.get(a.messageId) ?? [];
      list.push({ id: a.id, fileKey: a.fileKey, fileName: a.fileName, mimeType: a.mimeType, sizeBytes: a.sizeBytes });
      attsBy.set(a.messageId, list);
    }

    const mentionsBy = new Map<string, string[]>();
    for (const m of mentions) {
      const list = mentionsBy.get(m.messageId) ?? [];
      list.push(m.userId);
      mentionsBy.set(m.messageId, list);
    }

    const reactionsBy = new Map<string, { emoji: string; userIds: string[] }[]>();
    for (const r of reactions) {
      const list = reactionsBy.get(r.messageId) ?? [];
      let item = list.find((x) => x.emoji === r.emoji);
      if (!item) {
        item = { emoji: r.emoji, userIds: [] };
        list.push(item);
      }
      item.userIds.push(r.userId);
      reactionsBy.set(r.messageId, list);
    }

    const parentMap = new Map<string, { body: string | null; senderName: string }>();
    for (const p of parents) {
      parentMap.set(p.id, { body: p.body, senderName: p.senderName });
    }

    return rows.map((r) =>
      this.toMessageDto(
        r,
        attsBy.get(r.id) ?? [],
        mentionsBy.get(r.id) ?? [],
        r.parentMessageId ? (parentMap.get(r.parentMessageId) ?? null) : null,
        reactionsBy.get(r.id) ?? [],
      ),
    );
  }

  private toMessageDto(
    r: {
      id: string;
      conversationId: string;
      senderId: string;
      body: string | null;
      editedAt: Date | null;
      deletedAt: Date | null;
      createdAt: Date;
      parentMessageId: string | null;
      senderName: string;
      senderEmail: string;
      senderAvatar: string | null;
    },
    attachments: ChatAttachment[],
    mentionIds: string[],
    parentMessage: { body: string | null; senderName: string } | null,
    reactions: { emoji: string; userIds: string[] }[],
  ): ChatMessage {
    const deleted = !!r.deletedAt;
    return {
      id: r.id,
      conversationId: r.conversationId,
      sender: { id: r.senderId, name: r.senderName, email: r.senderEmail, avatarKey: r.senderAvatar },
      body: deleted ? null : r.body,
      attachments: deleted ? [] : attachments,
      mentionIds: deleted ? [] : mentionIds,
      parentMessageId: r.parentMessageId,
      parentMessage: deleted ? null : parentMessage,
      reactions: deleted ? [] : reactions,
      editedAt: r.editedAt ? r.editedAt.toISOString() : null,
      deletedAt: r.deletedAt ? r.deletedAt.toISOString() : null,
      createdAt: r.createdAt.toISOString(),
    };
  }

  private selectMessageWithSender() {
    return this.db
      .select({
        id: messages.id,
        conversationId: messages.conversationId,
        senderId: messages.senderId,
        body: messages.body,
        editedAt: messages.editedAt,
        deletedAt: messages.deletedAt,
        createdAt: messages.createdAt,
        parentMessageId: messages.parentMessageId,
        senderName: users.name,
        senderEmail: users.email,
        senderAvatar: users.avatarKey,
      })
      .from(messages)
      .innerJoin(users, eq(users.id, messages.senderId));
  }

  async listMessages(
    actor: Actor,
    conversationId: string,
    opts: { before?: string; limit?: number } = {},
  ): Promise<{ items: ChatMessage[]; hasMore: boolean; nextBefore: string | null }> {
    await this.assertCanAccess(conversationId, actor);
    const limit = Math.min(Math.max(opts.limit ?? 30, 1), 100);

    let beforeCreatedAt: Date | undefined;
    if (opts.before) {
      const [cursor] = await this.db
        .select({ createdAt: messages.createdAt })
        .from(messages)
        .where(and(eq(messages.id, opts.before), eq(messages.conversationId, conversationId)))
        .limit(1);
      beforeCreatedAt = cursor?.createdAt;
    }

    const rows = await this.selectMessageWithSender()
      .where(
        and(
          eq(messages.conversationId, conversationId),
          ...(beforeCreatedAt ? [lt(messages.createdAt, beforeCreatedAt)] : []),
        ),
      )
      .orderBy(desc(messages.createdAt), desc(messages.id))
      .limit(limit + 1);

    const hasMore = rows.length > limit;
    const page = rows.slice(0, limit);
    const items = (await this.hydrateMessages(page)).reverse(); // oldest → newest for the UI
    const nextBefore = hasMore ? page[page.length - 1]!.id : null;
    return { items, hasMore, nextBefore };
  }

  async getMessageForBroadcast(messageId: string): Promise<ChatMessage> {
    const [row] = await this.selectMessageWithSender().where(eq(messages.id, messageId)).limit(1);
    if (!row) throw new NotFoundException('Message not found');
    const [dto] = await this.hydrateMessages([row]);
    return dto!;
  }

  async sendMessage(actor: Actor, conversationId: string, input: SendMessageInput): Promise<ChatMessage> {
    await this.assertCanAccess(conversationId, actor);
    const body = input.body?.trim() ? input.body.trim() : null;
    const attachments = input.attachments ?? [];
    for (const a of attachments) {
      if (!ATTACHMENT_KEY.test(a.fileKey)) throw new BadRequestException('Invalid attachment reference');
    }

    const messageId = await this.db.transaction(async (tx) => {
      const [msg] = await tx
        .insert(messages)
        .values({
          conversationId,
          senderId: actor.id,
          body,
          parentMessageId: input.parentMessageId ?? null,
        })
        .returning({ id: messages.id });
      if (attachments.length) {
        await tx.insert(messageAttachments).values(
          attachments.map((a) => ({
            messageId: msg!.id,
            fileKey: a.fileKey,
            fileName: a.fileName,
            mimeType: a.mimeType,
            sizeBytes: a.sizeBytes,
          })),
        );
      }
      const mentionIds = Array.from(new Set(input.mentionIds ?? [])).filter((id) => id !== actor.id);
      if (mentionIds.length) {
        await tx.insert(messageMentions).values(mentionIds.map((userId) => ({ messageId: msg!.id, userId })));
      }
      const now = new Date();
      await tx
        .update(conversations)
        .set({ lastMessageAt: now, updatedAt: now })
        .where(eq(conversations.id, conversationId));
      // Sending implies the sender has read up to now.
      await tx
        .update(conversationMembers)
        .set({ lastReadAt: now })
        .where(
          and(eq(conversationMembers.conversationId, conversationId), eq(conversationMembers.userId, actor.id)),
        );
      return msg!.id;
    });

    return this.getMessageForBroadcast(messageId);
  }

  async editMessage(actor: Actor, messageId: string, body: string): Promise<ChatMessage> {
    const [row] = await this.db.select().from(messages).where(eq(messages.id, messageId)).limit(1);
    if (!row) throw new NotFoundException('Message not found');
    await this.assertCanAccess(row.conversationId, actor);
    if (row.senderId !== actor.id) throw new ForbiddenException('You can only edit your own messages');
    if (row.deletedAt) throw new BadRequestException('Cannot edit a deleted message');
    await this.db
      .update(messages)
      .set({ body: body.trim(), editedAt: new Date() })
      .where(eq(messages.id, messageId));
    return this.getMessageForBroadcast(messageId);
  }

  /** Soft-delete. Author always; group admins may remove others' messages. Returns the conversationId. */
  async deleteMessage(actor: Actor, messageId: string): Promise<{ conversationId: string }> {
    const [row] = await this.db.select().from(messages).where(eq(messages.id, messageId)).limit(1);
    if (!row) throw new NotFoundException('Message not found');
    const conv = await this.assertCanAccess(row.conversationId, actor);
    let allowed = row.senderId === actor.id;
    if (!allowed && conv.type === ConversationType.GROUP) {
      const [me] = await this.db
        .select({ isAdmin: conversationMembers.isAdmin })
        .from(conversationMembers)
        .where(
          and(
            eq(conversationMembers.conversationId, row.conversationId),
            eq(conversationMembers.userId, actor.id),
          ),
        )
        .limit(1);
      allowed = !!me?.isAdmin;
    }
    if (!allowed) throw new ForbiddenException('You cannot delete this message');
    if (!row.deletedAt) {
      await this.db.update(messages).set({ deletedAt: new Date(), body: null }).where(eq(messages.id, messageId));
      await this.db.delete(messageAttachments).where(eq(messageAttachments.messageId, messageId));
    }
    return { conversationId: row.conversationId };
  }

  async toggleReaction(actor: Actor, messageId: string, emoji: string): Promise<ChatMessage> {
    const [msg] = await this.db.select().from(messages).where(eq(messages.id, messageId)).limit(1);
    if (!msg) throw new NotFoundException('Message not found');
    await this.assertCanAccess(msg.conversationId, actor);
    if (msg.deletedAt) throw new BadRequestException('Cannot react to a deleted message');

    const [existing] = await this.db
      .select()
      .from(messageReactions)
      .where(
        and(
          eq(messageReactions.messageId, messageId),
          eq(messageReactions.userId, actor.id),
          eq(messageReactions.emoji, emoji),
        ),
      )
      .limit(1);

    if (existing) {
      await this.db
        .delete(messageReactions)
        .where(eq(messageReactions.id, existing.id));
    } else {
      await this.db
        .insert(messageReactions)
        .values({
          messageId,
          userId: actor.id,
          emoji,
        });
    }

    return this.getMessageForBroadcast(messageId);
  }

  async markRead(actor: Actor, conversationId: string, _messageId?: string): Promise<{ lastReadAt: string }> {
    await this.assertCanAccess(conversationId, actor);
    await this.ensureMemberRow(conversationId, actor.id);
    // Stamp with the DB clock (now()) so the value is at the same precision/source
    // as message created_at — a JS Date round-trip truncates sub-ms precision and
    // would leave the boundary message counted as unread.
    const [row] = await this.db
      .update(conversationMembers)
      .set({ lastReadAt: sql`now()` })
      .where(
        and(eq(conversationMembers.conversationId, conversationId), eq(conversationMembers.userId, actor.id)),
      )
      .returning({ lastReadAt: conversationMembers.lastReadAt });
    return { lastReadAt: (row?.lastReadAt ?? new Date()).toISOString() };
  }

  /* ── Members / detail / contacts ── */

  async getConversationDetail(actor: Actor, conversationId: string): Promise<ConversationDetail> {
    const conv = await this.assertCanAccess(conversationId, actor);
    const summary = await this.getConversationSummary(conversationId, actor.id);
    const members = await this.listMembers(conv);
    return { ...summary, members };
  }

  private async listMembers(conv: ConversationRow): Promise<ConversationMember[]> {
    if (conv.type === ConversationType.PROJECT) {
      const workspaceId = await this.projectWorkspaceId(conv.projectId!);
      const rows = await this.db
        .select({
          id: users.id,
          name: users.name,
          email: users.email,
          avatarKey: users.avatarKey,
        })
        .from(workspaceMembers)
        .innerJoin(users, eq(users.id, workspaceMembers.userId))
        .where(eq(workspaceMembers.workspaceId, workspaceId));
      return rows.map((u) => ({ user: this.toUserRef(u), isAdmin: false, lastReadAt: null }));
    }
    const rows = await this.db
      .select({
        id: users.id,
        name: users.name,
        email: users.email,
        avatarKey: users.avatarKey,
        isAdmin: conversationMembers.isAdmin,
        lastReadAt: conversationMembers.lastReadAt,
      })
      .from(conversationMembers)
      .innerJoin(users, eq(users.id, conversationMembers.userId))
      .where(eq(conversationMembers.conversationId, conv.id));
    return rows.map((u) => ({
      user: this.toUserRef(u),
      isAdmin: u.isAdmin,
      lastReadAt: u.lastReadAt ? u.lastReadAt.toISOString() : null,
    }));
  }

  private async assertGroupAdmin(actor: Actor, conversationId: string): Promise<ConversationRow> {
    const conv = await this.loadConversation(conversationId);
    if (conv.type !== ConversationType.GROUP) throw new BadRequestException('Not a group conversation');
    const [me] = await this.db
      .select({ isAdmin: conversationMembers.isAdmin })
      .from(conversationMembers)
      .where(
        and(eq(conversationMembers.conversationId, conversationId), eq(conversationMembers.userId, actor.id)),
      )
      .limit(1);
    if (!me) throw new ForbiddenException('You are not a member of this conversation');
    if (!me.isAdmin) throw new ForbiddenException('Only group admins can manage members');
    return conv;
  }

  async addMembers(actor: Actor, conversationId: string, memberIds: string[]): Promise<string[]> {
    await this.assertGroupAdmin(actor, conversationId);
    const found = await this.db
      .select({ id: users.id })
      .from(users)
      .where(and(inArray(users.id, memberIds), eq(users.isActive, true)));
    const validIds = found.map((u) => u.id);
    if (validIds.length === 0) throw new BadRequestException('No valid users to add');
    await this.db
      .insert(conversationMembers)
      .values(validIds.map((userId) => ({ conversationId, userId })))
      .onConflictDoNothing({ target: [conversationMembers.conversationId, conversationMembers.userId] });
    return validIds;
  }

  async removeMember(actor: Actor, conversationId: string, userId: string): Promise<void> {
    await this.assertGroupAdmin(actor, conversationId);
    await this.db
      .delete(conversationMembers)
      .where(
        and(eq(conversationMembers.conversationId, conversationId), eq(conversationMembers.userId, userId)),
      );
  }

  async getUserRef(userId: string): Promise<UserRef | null> {
    const [u] = await this.db
      .select({ id: users.id, name: users.name, email: users.email, avatarKey: users.avatarKey })
      .from(users)
      .where(eq(users.id, userId))
      .limit(1);
    return u ? this.toUserRef(u) : null;
  }

  async listContacts(actor: Actor, q?: string): Promise<ChatContact[]> {
    const like = q?.trim() ? `%${q.trim().toLowerCase()}%` : null;
    const rows = await this.db
      .select({
        id: users.id,
        name: users.name,
        email: users.email,
        avatarKey: users.avatarKey,
        designation: users.designation,
      })
      .from(users)
      .where(
        and(
          eq(users.isActive, true),
          ne(users.id, actor.id),
          ...(like ? [or(sql`lower(${users.name}) like ${like}`, sql`lower(${users.email}) like ${like}`)!] : []),
        ),
      )
      .orderBy(asc(users.name))
      .limit(30);
    return rows;
  }

  /** Authorize + resolve a chat attachment for streaming. */
  async attachmentForDownload(
    actor: Actor,
    fileKey: string,
  ): Promise<{ fileName: string; mimeType: string }> {
    const rows = await this.db
      .select({
        fileName: messageAttachments.fileName,
        mimeType: messageAttachments.mimeType,
        conversationId: messages.conversationId,
      })
      .from(messageAttachments)
      .innerJoin(messages, eq(messages.id, messageAttachments.messageId))
      .where(eq(messageAttachments.fileKey, fileKey));
    if (rows.length === 0) throw new NotFoundException('File not found');
    // The requester must have access to at least one conversation the file appears in.
    for (const r of rows) {
      try {
        await this.assertCanAccess(r.conversationId, actor);
        return { fileName: r.fileName, mimeType: r.mimeType };
      } catch {
        /* try the next conversation */
      }
    }
    throw new NotFoundException('File not found');
  }
}
