import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { http } from '../lib/api';
import { Button, Card, Input } from '../components/ui';
import { useWorkspaces, useUpdateWorkspace } from '../hooks/useWorkspaces';
type Unit = { id:string; name:string; timezone?:string; isArchived:boolean };
function Directory({ kind, title, timezone }: {kind:'offices'|'clients'|'teams';title:string;timezone?:boolean}) { const qc=useQueryClient(); const [name,setName]=useState(''); const [tz,setTz]=useState('Asia/Kolkata'); const q=useQuery({queryKey:['organisation',kind],queryFn:()=>http.get<Unit[]>(`/organisation/${kind}`)}); const add=useMutation({mutationFn:()=>http.post(`/organisation/${kind}`,timezone?{name,timezone:tz}:{name}),onSuccess:()=>{setName('');qc.invalidateQueries({queryKey:['organisation',kind]})}}); return <Card className="p-5"><h2 className="font-bold">{title}</h2><div className="mt-3 flex gap-2"><Input value={name} onChange={e=>setName(e.target.value)} placeholder={`New ${title.slice(0,-1).toLowerCase()}`} />{timezone&&<Input value={tz} onChange={e=>setTz(e.target.value)} />}<Button onClick={()=>add.mutate()} disabled={!name||add.isPending}>Add</Button></div><ul className="mt-4 space-y-2 text-sm">{q.data?.map(x=><li key={x.id} className="rounded bg-slate-50 p-2 dark:bg-slate-800">{x.name}{x.timezone?` · ${x.timezone}`:''}</li>)}</ul></Card> }
function WorkspaceContext(){const {data:ws=[]}=useWorkspaces();const {data:offices=[]}=useQuery({queryKey:['organisation','offices'],queryFn:()=>http.get<Unit[]>('/organisation/offices')});const {data:clients=[]}=useQuery({queryKey:['organisation','clients'],queryFn:()=>http.get<Unit[]>('/organisation/clients')});const [id,setId]=useState('');const selected=ws.find(w=>w.id===id);const update=useUpdateWorkspace(id);return <Card className="mt-6 p-5"><h2 className="font-bold">Workspace context</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><select className="rounded border p-2 dark:bg-slate-800" value={id} onChange={e=>setId(e.target.value)}><option value="">Choose workspace</option>{ws.filter(w=>!w.isArchived).map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select><select disabled={!id} className="rounded border p-2 dark:bg-slate-800" value={selected?.officeId??''} onChange={e=>update.mutate({officeId:e.target.value||null})}><option value="">No office</option>{offices.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select disabled={!id} className="rounded border p-2 dark:bg-slate-800" value={selected?.clientId??''} onChange={e=>update.mutate({clientId:e.target.value||null})}><option value="">No client</option>{clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div></Card>}
export function OrganisationPage(){return <div><h1 className="text-2xl font-extrabold">Organisation</h1><p className="mt-1 text-sm text-slate-500">Locations, customers and internal teams. Workspace membership remains the access boundary.</p><div className="mt-6 grid gap-4 lg:grid-cols-3"><Directory kind="offices" title="Offices" timezone/><Directory kind="clients" title="Clients"/><Directory kind="teams" title="Teams"/></div><WorkspaceContext/></div>}
